/*
# Teams Tenancy Columns

## Purpose
Adds organization-isolation columns to the `teams` table so that when an
access request is approved, the new team row carries the director's contact
info and a unique org_code that members use to join.

## Changes to `teams`

### Added columns
1. `org_code` (text, nullable, UNIQUE)
   - 6-character alphanumeric code generated by the approve-request edge function
   - Members enter this code at signup to join the correct org
   - Unique constraint prevents two orgs from sharing a code

2. `org_type` (text, nullable)
   - Copied from the access request (e.g. "Adult Bass Club", "College Team")
   - Lets the app distinguish club vs. team features

3. `director_name` (text, nullable)
   - Name of the person who submitted the access request
   - Shown in the club dashboard as the club director

4. `director_email` (text, nullable)
   - Email of the director (copied from access request)
   - Used for communication and as the contact of record

5. `director_phone` (text, nullable)
   - Phone of the director (copied from access request, if provided)

6. `status` (text, NOT NULL, default 'active')
   - Lifecycle of the org: 'active' (approved), 'inactive' (disabled)
   - New orgs created by approve-request get 'active'

## Security
- No RLS policy changes — existing policies on `teams` are unchanged.
- The UNIQUE constraint on `org_code` is a data-integrity safeguard, not a
  security control.

## Important Notes
1. Idempotent — uses IF NOT EXISTS guards on every ADD COLUMN.
2. The UNIQUE constraint uses `IF NOT EXISTS` via a DO block for idempotency,
   since `CREATE UNIQUE INDEX` does not support IF NOT EXISTS on all PG versions
   in the same way.
3. Existing team rows (if any) will have NULL for org_code/org_type/director_*
   and 'active' for status — this is intentional and does not break existing
   functionality.
*/

-- 1. Add tenancy columns
ALTER TABLE teams ADD COLUMN IF NOT EXISTS org_code text;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS org_type text;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS director_name text;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS director_email text;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS director_phone text;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';

-- 2. Add unique index on org_code (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public'
    AND tablename = 'teams'
    AND indexname = 'teams_org_code_unique'
  ) THEN
    CREATE UNIQUE INDEX teams_org_code_unique ON teams(org_code) WHERE org_code IS NOT NULL;
  END IF;
END $$;
